### ISSUE TITLE
task 33 failed - "y is constant; gaussian glmnet fails at standardization step"

### ISSUE THREAD

**Issue by Eismeer** [JunLiuLab/SIMPLEs#6]
Hi! Thank you for the algorithm. 

There is a problem difficult for me to solve. Every time I wanted to use the data simulated by [splatter](https://github.com/Oshlack/splatter), it threw this error:
`Error in { :`
`  task 33 failed - "y is constant; gaussian glmnet fails at standardization step"`
`Calls: SIMPLE -> %dopar% -> <Anonymous>`
The number after "task" changed every time.

But if I use real data instead of simulation data, such things won't happen. What does this error mean? How can I solve it?

Thank you for your time.

**Comment by beyondpie** [comment]
Hi Eismeer,

Thanks for your interest in this algorithm. I guess the simulation from the splatter causes the constant of y, which is defined below in our [supplementary](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/nargab/2/4/10.1093_nargab_lqaa077/2/lqaa077_supplemental_file.pdf?Expires=1618413978&Signature=QpXDFpC~GY7kxf3NT4jwsdns7x9h0q6JZVau-WRggTOVaj-INnD0U0EhiK2vlsGoWHH1fjtwYE3RLfK4HJUXmXn9D5kJzQfmbH-r6MxPeReXprF3z7tUAXeNOwum8ORoipPn74rOHDCoi~~UhUdWtLiVpBl~e-yRMVsR9109jSj9Sg6XUPHsLO4KvsH2oD83b6okdlmwC~dMAOgxBiMXoEW9sXsELGWgw73gzzVC9ofWjgEi2GNrTu8PGDWX6CQfMB5QsUzFzLQRyIrKdxs1MSAaqO4ziODTxKlxnY16NZaqrsgoKel0zD4r00QrUA6bHuHo6-Tl6nsfDLxU6xXs0Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA):
![image](https://user-images.githubusercontent.com/6449478/110653965-b7dbba80-818b-11eb-8d96-0d2a8ec67ccb.png)

So is that because in your simulation,  the cells from the same cell cluster will have the identical expression for each gene ?

@xyz111131 plz correct me if I make mistakes here.

**Comment by xyz111131** [comment]
The number after "task" changed every time: we iterate all the genes in parallel, task number indicates which gene has problem, but the order of the genes might change. 

yes, it's because "\tilde y" in the expression is constant. perhaps adding some noise to y? How many clusters are there? If you still have trouble running it, you can send us the data matrix generated by splatter or the command you used to generate the data.

**Comment by Eismeer** [comment]
Thanks for your answers. 

There're six clusters. I've checked the expression in the same clusters, but the cells within don't have an identical expression for each gene.

Here's my code to generate the data:

```
# Simulation
suppressPackageStartupMessages({
  library(splatter)
  library(scater)
})
sc.params <- newSplatParams(nGenes = 2000, batchCells = 500,
                            group.prob = rep(1/6, 6),
                            dropout.type = 'experiment',
                            dropout.mid = 0.8, seed = 912)

sim.sce <- splatSimulate(sc.params, method = "group",
                         verbose = F)

sim.counts <- as.matrix(assays(sim.sce)$counts)

# Excerpt the grouping situation
sim.groups <- data.frame(rownames(colData(sim.sce)))
sim.groups$V2 <- colData(sim.sce)$Group
colnames(sim.groups) <- c('cell', 'group')

# Normalization
library(scuttle)
sim.norm <- logNormCounts(sim.sce, log = T)
norm.counts <- as.matrix(logcounts(sim.norm))

write.table(sim.groups, 'drop41_groups.csv', row.names = T, col.names = F, sep = ",")
write.table(norm.counts, 'drop41_norm.csv', row.names = T, col.names = T, sep = ",")
```

I've added noise by setting the parameter `dropout.type` and `dropout.mid`. Is that the kind of noise needed? 

Then I used SIMPLEs in another RScript:

```
d41.groups <- read.csv('drop41_groups.csv', header = F)
d41.groups <- d41.groups[-1]
colnames(d41.groups) <- c('cell', 'group')
group.num <- length(group.name)

d41.norm <- as.matrix(read.csv('drop41_norm.csv'))

d41.simples <- SIMPLE(d41.norm, M0 = group.num,
                                      min_gene = 200, cutoff = 0.01)
```

**Comment by xyz111131** [comment]
Thanks for sending the code. The problem is that in the data matrix, there are genes with zero expression in all the cells. Those genes need to be filtered out: e.g. adding `data.filter = d41.norm[rowSums(d41.norm>0.01)>9,]` which filtered out genes that expressed in less than 10 cells.

**Comment by Eismeer** [comment]
Problem solved! Thanks for looking for the problem patiently.
